### ISSUE TITLE
Issue with pytlu in development branch

### ISSUE THREAD

**Issue by BothoP** [SiLab-Bonn/pytlu#17]
With current commit bb5b8414fb7f84509349abe7ed6c2ea67d43c467
I get the following problem

> [paschen@boblap ~]$ pytlu -ie CH0 -oe CH0 -t 40000 -c 99
> 2018-10-30 11:25:59,287 [INF] Loading configuration file from /home/paschen/pytlu/pytlu/tlu.yaml
> 2018-10-30 11:25:59,288 [INF] Log file name: /home/paschen/pytlu/pytlu/output_data/20181030_112559_tlu.log
> 2018-10-30 11:25:59,288 [INF] Data file name: /home/paschen/pytlu/pytlu/output_data/20181030_112559_tlu.h5
> 2018-10-30 11:25:59,289 [INF] Initializing Tlu
> 2018-10-30 11:25:59,342 [INF] Found TLU(s): ZestSC1 with ID 1 (Serial no. 3088)
> 2018-10-30 11:25:59,343 [INF] Using TLU: None
> Traceback (most recent call last):
>  File "/home/paschen/miniconda2/bin/pytlu", line 11, in <module>
>    load_entry_point('pytlu', 'console_scripts', 'pytlu')()
>  File "/home/paschen/pytlu/pytlu/tlu.py", line 304, in main
>    chip.init()
>  File "/home/paschen/pytlu/pytlu/tlu.py", line 104, in init
>    super(Tlu, self).init()
>  File "/home/paschen/miniconda2/lib/python2.7/site-packages/basil_daq-2.4.12-py2.7.egg/basil/dut.py", line 119, in init
>    catch_exception_on_init(item)
>  File "/home/paschen/miniconda2/lib/python2.7/site-packages/basil_daq-2.4.12-py2.7.egg/basil/dut.py", line 113, in catch_exception_on_init
>    mod.init()
>  File "/home/paschen/pytlu/pytlu/ZestSC1TL.py", line 47, in init
>    self._dev.open_card()
> AttributeError: 'NoneType' object has no attribute 'open_card'

with commit e1b52c34d4c5eb3436f8fb8629711f4571c7e2b2 it works without a problem

**Comment by laborleben** [comment]
Should be fixed. Please test.

**Comment by BothoP** [comment]
Works, thanks.
