### ISSUE TITLE
No python2 compability anymore

### ISSUE THREAD

**Issue by YannickDieter** [SiLab-Bonn/pytlu#23]
I just realized that python2 compability is lost due to [this](https://github.com/SiLab-Bonn/pytlu/blob/development/pytlu/ZestSC1.py#L210).

Should we just drop python2 support or fix it @DavidLP @themperek @laborleben ?

**Comment by themperek** [comment]
If this it is easy, please fix for now.

**Comment by DavidLP** [comment]
I guess the monolithic people have not changed to python 3? @thirono

**Comment by laborleben** [comment]
A fix for both Python 2.7 and 3 should be doable. Why hesitate?

**Comment by YannickDieter** [comment]
You are completely right. Issue is fixed now.
